/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <math.h>
#include "stm32f7xx.h"

#include "arm_math.h"

#include "rcc.h"
#include "gpio.h"
#include "timer.h"
#include "interrupt.h"
#include "adc.h"
#include "dma.h"
#include "dac.h"

#include "control.h"

volatile float TEMPERATURE;
volatile float arg_rad;

int main(void)
{
    // Включение DWT (счётчик тактов, Program Counter)
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk; // Armv7-M Architecture Reference Manual, p. C1-706.
    DWT->LAR = 0xC5ACCE55;                          // ARM CoreSight Architecture Specification (v3.0), p. B2-61.
    DWT->CYCCNT = 0;                                // Armv7-M Architecture Reference Manual, p. C1-731.
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;            // Armv7-M Architecture Reference Manual, p. C1-740.

    // Глобальное отключение прерываний.
    __disable_irq();

    //init_INTERRUPT();

    init_INTERRUPT();
    init_RCC();
    init_DAC();
    init_GPIO();
    init_DMA();
    init_ADC();
    init_TIMER8();

    // Ожидание включения периферии.
    for(int i = 0; i < 5000; i++);

    // Глобальное включение прерываний.
    __enable_irq();

    /* Loop forever */
    for(;;)
    {
        //for(int i = 0; i < 100000; i++);
        //GPIOD->ODR ^= 1 << 1;

        // Проверяем PB1 (SW1) на ноль.
        if (!(GPIOB->IDR & (1 << 1)))
            Boost_Measure.count = SET_SHIFTS_MAX_COUNT;

        // Проверяем PB2 (SW2) на ноль.
        if (!(GPIOB->IDR & (1 << 2)))
        {
            extern float REF_CONTROLLER;

            REF_CONTROLLER = IL_REF_1;

            timer_PWM_On();
            GPIOD->ODR &= ~((1 << 1) | (1 << 2) | (1 << 3) | (1 << 4) | (1 << 5));
        }
    }
}


void SINE_COSINE_FUNCTION(void)
{
float sin[4], csine[4];

cost float arg_rad = arg*(float)MP_I/180.f;

// Функции из стандартной библиотеки языка си
TIC = DWT->CYCCNT;
sine[0]= sinf(arg_rad);
cosine[0] = cosf(arg_rad);

TOC[0] = DWT->CYCCNT - TIC;
TIC = DWT->CYCCNT;

sine[1] = arm_sin_f32(arg_rad);
cosine[1]= arm_cosine_f32(arg_rad);

TOC[1] = DWT->CYCCNT - TIC;
TIC = DWT->CYCCNT;

arm_sin_cos_f32(arg_rad);
cosine[1]= arm_cosine_f32(arg_rad);

TOC[1] = DWT->CYCCNT - TIC;
TIC = DWT->CYCCNT;

}

void float asinf()
{



}




